# Generated by Django 5.2.7 on 2025-11-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('overdue', 'Overdue')], default='active', max_length=20),
        ),
    ]
