# Generated by Django 5.2.7 on 2025-12-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringexpense',
            name='last_reminder_days',
            field=models.IntegerField(blank=True, help_text='Last reminder sent (days before due date)', null=True),
        ),
    ]
